### PR TITLE
Tomm/getting started

### LINKED ISSUE #2: Setup eslint
- [x] Install eslint
 - [x] Install eslint-plugin-jest
 - [x] Setup `.eslintrc.js`

### PR DESCRIPTION
**Pull request by MuckT**
### Description

This PR set up the initial client scaffolding and linting.

Fixes: #2 #1 #5

### CODE REVIEW

**Review by antoni909 — APPROVED** [review]
looks a-okay

**Review by markjackson28 — APPROVED** [review]
Nice!

**Review by antoni909 — COMMENTED** [review]
review again

**Review by antoni909 — APPROVED** [review]
...approved

**Review by vbchomp — APPROVED** [review]

**Pull request merged**
